# Generated by Django 5.2.4 on 2025-08-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sitesetting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="address",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="copyright",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="default_image",
            field=models.ImageField(blank=True, null=True, upload_to="photos/default/"),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="phone_number",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="site_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="site_title",
            field=models.CharField(default="MarketPlace", max_length=200),
        ),
    ]
