# Generated by Django 5.2.4 on 2025-07-08 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="author_name",
            new_name="name",
        ),
    ]
