# Generated by Django 5.2.4 on 2025-07-19 08:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_rename_author_name_blog_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Category",
            new_name="BlogCategory",
        ),
        migrations.RemoveField(
            model_name="blog",
            name="name",
        ),
        migrations.AddField(
            model_name="blog",
            name="status",
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name="blog",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
