# Generated by Django 5.2.4 on 2025-07-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0003_rename_category_blogcategory_remove_blog_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="blog_image",
            field=models.ImageField(blank=True, null=True, upload_to="photos/blogs"),
        ),
    ]
