# Generated by Django 5.2.4 on 2025-08-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_product_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="status",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
