# Generated by Django 5.2.4 on 2025-08-18 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_category_status_alter_product_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
